# Generated by Django 4.2.11 on 2024-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_image_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='availability',
            field=models.CharField(default='Red', max_length=5),
        ),
    ]
