# Generated by Django 4.2.11 on 2024-05-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
